#! /usr/bin/env python3
#
#  ldapgroup - Manage LDAP groups.
#
#  (C) 2018-2019 Richard Neumann <mail at richard dash neumann period de>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
"""Manage LDAP groups."""

from logging import INFO, basicConfig, getLogger
from sys import argv

from ldaptools.cli import LOG_FORMAT
from ldaptools.cli.ldapgroup import get_args
from ldaptools.config import CONFIG
from ldaptools.functions import ldapadd, ldapmodify
from ldaptools.group import create, modify, add, remove
from ldaptools.ldif import DistinguishedName


LOGGER = getLogger(argv[0])


def _add(args):
    """Adds an LDAP group."""

    ou = args.ou or CONFIG['group']['ou']
    domain = args.domain or CONFIG['common']['domain']
    ldif = create(args.name, args.gid, args.member, ou=ou, domain=domain)
    master = DistinguishedName.for_master(domain)
    ldapadd(master, ldif)


def _modify(args):
    """Modifies an LDAP group."""

    ou = args.ou or CONFIG['group']['ou']
    domain = args.domain or CONFIG['common']['domain']
    ldif = modify(args.name, gid=args.gid, ou=ou, domain=domain)
    master = DistinguishedName.for_master(domain)
    ldapmodify(master, ldif)


def _add_member(args):
    """Adds a member to an LDAP group."""

    ou = args.ou or CONFIG['group']['ou']
    domain = args.domain or CONFIG['common']['domain']

    for member in args.member:
        ldif = add(args.group, member, ou=ou, domain=domain)
        master = DistinguishedName.for_master(domain)
        ldapmodify(master, ldif)


def _remove_member(args):
    """Removes a member from an LDAP group."""

    ou = args.ou or CONFIG['group']['ou']
    domain = args.domain or CONFIG['common']['domain']

    for member in args.member:
        ldif = remove(args.group, member, ou=ou, domain=domain)
        master = DistinguishedName.for_master(domain)
        ldapmodify(master, ldif)


def main():
    """Main function."""

    args = get_args()
    basicConfig(level=INFO, format=LOG_FORMAT)

    if args.action == 'add':
        _add(args)
    elif args.action == 'modify':
        _modify(args)
    elif args.action == 'add-member':
        _add_member(args)
    elif args.action == 'remove-member':
        _remove_member(args)
    else:
        LOGGER.error('No action specified.')


if __name__ == '__main__':
    main()
